import filmIndex from '@/data/archive/filmIndex.json'
import type { StoryEvent } from '@/data/story/types'
import type { MaterialClass } from '@/data/archive/types'
import { isExcludedFromFilm } from '@/data/archive/placement'

/**
 * The film's picture library (generated by `npm run import:archive` from the research manifest):
 * per storyboard beat, only images that may appear in the cinematic layer — held locally,
 * rights clear or likely clear, real material (never a reconstruction or stand-in), ordered
 * hero → archive → map → newspaper → document → context. Small and synchronous, so the camera
 * can plan cutaways; the full catalogue stays lazy in the archive repository.
 */
export interface FilmPrint {
  id: string
  title: string
  filmPath: string
  filmHiPath?: string
  thumbPath?: string
  width?: number
  height?: number
  year: number
  date?: string
  credit?: string
  source?: string
  materialClass: MaterialClass
  imageClass?: string
  eventIds: string[]
}

const INDEX = filmIndex as unknown as Record<string, FilmPrint[]>
const BY_ID = new Map<string, FilmPrint>()
for (const list of Object.values(INDEX)) for (const p of list) BY_ID.set(p.id, p)

// Every frame that has real photographs gets a small pile (2005 is the reference), never filler:
// images that do not show the frame's subject are kept off the table (data/archive/placement).
const CAP = { major: 4, featured: 3, standard: 2 } as const

/** The table holds four prints at most (plateFrame.printSlots). */
const TABLE_MAX = 4

export function filmPrintsFor(event: StoryEvent, cap?: number): FilmPrint[] {
  // Hand-placed prints always fit (up to the table's four); the index only tops up to the cap.
  cap ??= Math.min(TABLE_MAX, Math.max(CAP[event.importance], event.visualTreatment.prints?.length ?? 0))
  const out: FilmPrint[] = []
  const seen = new Set<string>()
  for (const id of event.visualTreatment.prints ?? []) {
    const p = BY_ID.get(id)
    if (p && !seen.has(id)) {
      out.push(p)
      seen.add(id)
    }
  }
  for (const p of INDEX[event.id] ?? []) {
    if (out.length >= cap) break
    if (!seen.has(p.id) && !isExcludedFromFilm(event.id, p.id)) {
      out.push(p)
      seen.add(p.id)
    }
  }
  return out.slice(0, cap)
}

export function hasHero(event: StoryEvent): boolean {
  return filmPrintsFor(event, 1).length > 0
}

export function filmPrintCount(): number {
  return BY_ID.size
}
